### ISSUE TITLE
Attribute error of subprocess when working with python 2.7

### ISSUE THREAD

**Issue by doug919** [stanfordnlp/python-stanford-corenlp#26]
I got the following error when working with python 2.7

python-stanford-corenlp/corenlp/client.py", line 72, in start
    stderr = subprocess.DEVNULL if self.be_quiet else self.stderr
AttributeError: 'module' object has no attribute 'DEVNULL'

I tried to upgrade subprocess32:
```
$ pip install --upgrade subprocess32
Collecting subprocess32
Installing collected packages: subprocess32
Successfully installed subprocess32-3.5.3
```
But the issue stayed the same.

**Comment by arunchaganty** [comment]
I've fixed that command to be backwards compatible with python 2.7.
